
import os

'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

#Iterate Fib

Fib_a = 1
Fib_b = 2
Fib = 0
Fib_sum = 0
upper_limit = 4000000

def is_even_integer(integer):
    return integer & 1 == 0

while Fib_b < upper_limit:
    Fib = Fib_a + Fib_b
    Fib_a = Fib_b
    if is_even_integer(Fib_b):
        Fib_sum = Fib_sum + Fib_b
    Fib_b = Fib

print(Fib_sum)
