import os
import math
import time

"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

#Slight optimization,-0.1ms, due to every triangle number is a hexagonal number

def hexagonal(n):
    return (n*(2*n-1))

def is_pentagonal(t):
    n = (1+math.sqrt(1+24*t))/6
    return n == math.floor(n)

if __name__ == '__main__':
    stime = time.time()
    n = 143
    while(True):
        n += 1
        next_hexagonal = hexagonal(n) 
        if is_pentagonal(next_hexagonal):
            break

    print("Solution: {0}\n Runtime: {1}".format(next_hexagonal,time.time()-stime))
    pass
